@startuml
'https://plantuml.com/sequence-diagram

skinparam classFontStyle Bold
hide empty members

Package DxD {
Package personnage {
class Personnage {
    - nom: String
    - race: Race
    - classe: Classe
    - pointsDeVie: int
    - force: int
    - dexterite: int
    - vitesse: int
    - initiative: int
    - inventaire: List<Equipement>
    - armeEquipee: Arme
    - armureEquipee: Armure
    + <<create>> Personnage (nom,race,classe)
    + seDeplacer(): void
    + attaquer(cible: Monstre): void
    + sEquiper(equipement: Equipement): void
    }
}

Package race {
abstract Race {
    + {abstract} appliquerRace(personnage: Personnage): void
}

class Elf extends Race{
    + <<class>> Elf()
    + appliquerRace(personnage: Personnage): void
}

class Halfelin extends Race {
    + <<class>> Halfelin()
    + appliquerPouvoir(personnage: Personnage): void
}

class Human extends Race {
    + <<class>> Human()
    + appliquerRace(personnage: Personnage): void
}

class Dwarf extends Race {
    + <<class>> Dwarf()
    + appliquerRace(personnage: Personnage): void
    }
}

Package classe {
abstract Classe {
    + {abstract} appliquerPouvoir(personnage: Personnage): void

    }
class Guerrier extends Classe {
    + <<create>> Guerrier()
    + appliquerPouvoir(personnage: Personnage): void
    }
class Magicien extends Classe {
    + <<create>> Magicien()
    + appliquerPouvoir(personnage: Personnage): void
}
class Clerc extends Classe {
    + <<create>> Clerc()+
    + appliquerPouvoir(personnage: Personnage): void
}
class Roublard extends Classe {
    + <<create>> Roublard()
    + appliquerPouvoir(personnage: Personnage): void
    }
}

Package monstre {
class Monstre {
    - nom: String
    - pointsDeVie: int
    - force: int
    - dexterite: int
    - vitesse: int
    + <<create>> Monstre()
    + attaquer(cible: Personnage): void
    }

}

Package equipement {
abstract class Equipement {
    - nom: String
    + <<create>> Equipement()
    + utiliser(): void
}

class Arme extends Equipement {
    - degats: String
    - portee: int
    + <<create>> Arme()
    + attaquer(): void
}

class Armure extends Equipement  {
    - classeArmure: int
    + <<create>> Armure()
    }
   }

class Donjon {
    - carte: List<List<String>>
    - obstacles: List<String>
    - monstres: List<Monstre>
    - personnages: List<Personnage>
    + <<create>> Donjon()
    + miseEnPlace(): void
    + jouerTour(): void
    + verifierFin(): boolean
    }

Personnage  *--> "1 -race " Race : possède
Personnage  *--> "1 -class " Classe : possède

Personnage "1" *-- "1 -armeEquipee" Arme : équipe
Personnage "1" *-- "1 -armeArmure" Armure : équipe

Donjon "1" *-- "0..*" Monstre
Donjon "1" *-- "0..*" Personnage

}




@enduml